### ISSUE TITLE
chore: update github

### ISSUE THREAD

**Issue by xafn** [aaxyria/axyria.dev#26]
<img width="207" alt="image" src="https://user-images.githubusercontent.com/47723802/235467892-23823a38-f13a-405f-b33c-12293cae3619.png">
<img width="52" alt="image" src="https://user-images.githubusercontent.com/47723802/235467942-b3212a50-5a86-47aa-ae4b-b1122fe7599c.png">

stop changing your username (explode)

**Comment by aaxyria** [comment]
ong thanks for reminding me :trollface:

**Comment by aaxyria** [comment]
oh i forgor
